# Generated by Django 3.0.13 on 2021-03-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210316_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='default.jpg', upload_to='articles'),
        ),
    ]
